###Environment & Database Seeding Setup###
POST http://localhost:8000/api/reset


### Test 2: Fetch Primary Dashboard Aggregation Feed
GET http://localhost:8000/api/dashboard HTTP/1.1
Accept: application/json
User-Agent: GreenStepTestClient/1.0


###Activity Type Coefficients Directory###
GET http://localhost:8000/api/activities/types


###Post a Carbon Footprint Activity Log (Success State)###
POST http://localhost:8000/api/activities/log
Content-Type: application/json
Accept: application/json

{
  "activity_type_id": 5,
  "amount": 2,
  "date": "2026-06-16"
}


###Validation Rules: Missing Log Payload Attributes###
POST http://localhost:8000/api/activities/log
Content-Type: application/json

{
  "amount": 10
}